### ISSUE TITLE
Add configurability

### ISSUE THREAD

**Issue by scott-steadman** [ss/rails_monitoring_engine#11]
## Why?
Developers need to be able to enable/disable the engine
and determine what to track.

## Details
MVP Example Usage:
```ruby
# config/initializers/rails_monitoring_engine.rb

RailsMonitoringEngine.enable!
```

More complete example Usage:
```ruby
# config/initializers/rails_monitoring_engine.rb

RailsMonitoringEngine.configure do
  enable!
end
```

 - Configuration is a class in case we need multiple configurations (eg one per thread)

## Tasks
 - [x] 1) Create configuration class.

### Testing
- [x] 100% coverage

### Documentation
- [x] Update README.md
- [x] Update Wiki [Configuration-Options](https://github.com/ss/rails_monitoring_engine/wiki/Configuration-Options)
