### ISSUE TITLE
Add data visualization

### ISSUE THREAD

**Issue by scott-steadman** [ss/rails_monitoring_engine#5]
## Why?
Users need to be able to view and manipulate the timing data

## Details
This should look like NewRelic's performance graph.

## Tasks
- [ ] 1) Make sure user has privileges
- [ ] 2) Render graph
- [ ] 3) Allow user to change number of data points
- [ ] 4) Allow user to change interval (minimum 1-second)
- [ ] 5) Allow user to change start/end times
- [ ] 6) Make sure pages are responsive

### Testing
- [ ] 100% coverage

### Documentation
- [ ] Update Wiki
